app:
  name: provider
  registry:
    address: 127.0.0.1:2181

  server:
    port: 8887

rpc:
  registry:
    group: dubbo
  protocl:
    name: dubbo
    port: 28883

#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql:///hundsun?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123123
logging:
  level:
    root: info
  path: /Users/wangcan/log
  file: /Users/wangcan/log/log_provider_01.log